<?php
declare(strict_types=1);
require __DIR__ . '/config.php';

$reference = strtoupper(trim((string)($_GET['ref'] ?? $_POST['reference'] ?? '')));
$report = null; $error = '';
$states = ['received' => ['Report received', 'Your report has entered the monitoring queue.', 'blue'], 'verified' => ['Report verified', 'A monitoring administrator has reviewed the report.', 'amber'], 'dispatched' => ['Response in motion', 'A response team has been assigned for coordination.', 'violet'], 'resolved' => ['Report resolved', 'The monitoring team has marked this incident resolved.', 'green']];
if ($_SERVER['REQUEST_METHOD'] === 'POST') verify_csrf($_POST['csrf_token'] ?? null);
if ($reference !== '') {
    if (!rate_limit('track-lookup', 60, 60)) $error = 'Too many status checks were made from this connection. Please wait a minute and try again.';
    else try { $report = app()->incidents->findPublic($reference); } catch (Throwable $exception) { log_app_error($exception); $error = 'The monitoring record is temporarily unavailable. Try again shortly.'; }
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Track report · iMSafe v2.0</title><link rel="stylesheet" href="assets/app.css?v=5"><link rel="stylesheet" href="assets/navigation.css?v=9"><link rel="stylesheet" href="assets/atmosphere.css?v=5"><link rel="stylesheet" href="assets/imassist.css?v=2"></head><body class="public-body"><?php require __DIR__ . '/partials/header.php'; ?><main id="main-content" tabindex="-1" class="track-layout"><section class="track-copy"><p class="section-kicker">Public report follow-up</p><h1>Track an incident<br> <span>with confidence.</span></h1><p>Use the reference code given after a rapid assessment. This page shares only the current progress of the incident.</p><div class="trust-note">✓ Full report details and contact information are kept private.</div></section><section class="track-panel"><div class="track-panel-heading"><span aria-hidden="true">⌕</span><div><h2>Find a report</h2><p>Reference codes look like <b>IMS-ABC123-1234567890ABCDEF</b>.</p></div></div><form id="trackForm" class="track-search" method="post"><input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>"><label for="reference">Report reference code</label><div><input id="reference" name="reference" value="<?= h($reference) ?>" placeholder="IMS-…" autocomplete="off" required><button type="submit"><i aria-hidden="true">⌕</i><span>Check status</span></button></div><p id="trackValidation" class="inline-error" role="alert" hidden></p></form><?php if ($error !== ''): ?><div class="status-message error" role="alert">⚠ <?= h($error) ?></div><?php elseif ($reference !== '' && !$report): ?><div class="status-message neutral" role="status">⌕ <span><b>No matching report found</b>Check the reference code and try again.</span></div><?php elseif ($report): $state = $states[$report['status']] ?? $states['received']; ?><div class="tracked-card"><div class="status-banner <?= h($state[2]) ?>"><span aria-hidden="true">✓</span><div><small>Current status</small><h3><?= h($state[0]) ?></h3><p><?= h($state[1]) ?></p></div></div><dl><div><dt>Report reference</dt><dd><?= h($report['reference_code']) ?></dd></div><div><dt>Submitted</dt><dd><?= h(date('M j, Y · g:i A', strtotime($report['created_at']))) ?></dd></div><div><dt>Incident type</dt><dd><?= h($report['specific_type']) ?></dd></div><div><dt>Location</dt><dd><?= h($report['barangay_name'] . ', ' . $report['municipality_name']) ?></dd></div></dl><?php if (!empty($report['note'])): ?><div class="public-update"><b>Latest update</b><?= h($report['note']) ?></div><?php endif; ?></div><?php endif; ?></section></main><script src="assets/track.js?v=5"></script><?php require __DIR__ . '/partials/footer.php'; ?>
</body></html>
